name: crud_de_games_educacional
description: Mini projeto CRUD de controle de jogos em Flutter com API PHP e MySQL.
publish_to: "none"
version: 2.0.0+3

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
